# Copyright 2024 The vLLM team.
# Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
#
# This test is based on the structure of test_rotary_embedding.py

from typing import Optional

import pytest
import torch
import torch.nn as nn

from vllm_ascend.utils import enable_custom_op

# 启用 vllm-ascend 的自定义算子
enable_custom_op()

# --- 测试参数定义 ---
DTYPES = [torch.bfloat16]  # 我们只测试 bfloat16
NUM_TOKENS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]  # 测试不同的 token 数量
HIDDEN_SIZES = [2048]  # 测试不同的隐藏层大小
INTERMEDIATE_SIZES = [11008]  # 测试不同的中间层大小
SEEDS = [0]
DEVICES = [f"npu:{i}" for i in range(torch.npu.device_count())]

# 默认的精度容忍度
DEFAULT_ATOL = 1e-2
DEFAULT_RTOL = 1e-3


# --- 参考实现 (Golden Standard) ---

class Qwen2MLPReference(nn.Module):
        """
            一个纯 PyTorch 的 Qwen2 FFN 实现，用于与自定义内核进行对比。
                """

                    def __init__(
                                    self,
                                            hidden_size: int,
                                                    intermediate_size: int,
                                                            dtype: torch.dtype,
                                                                    device: Optional[str] = None,
                                                                        ) -> None:
                                super().__init__()
                                        # 模拟 MergedColumnParallelLinear
                                                self.gate_up_proj = nn.Linear(hidden_size, 2 * intermediate_size, bias=False, dtype=dtype, device=device)
                                                        # 模拟 RowParallelLinear
                                                                self.down_proj = nn.Linear(intermediate_size, hidden_size, bias=False, dtype=dtype, device=device)
                                                                        # SiLU 激活函数
                                                                                self.act_fn = nn.SiLU()

                                                                                    def forward(self, x: torch.Tensor) -> torch.Tensor:
                                                                                                # 1. gate_up_proj
                                                                                                        # 使用有意义的变量名 gate_proj 和 up_proj
                                                                                                                gate_proj, up_proj = self.gate_up_proj(x).chunk(2, dim=-1)
                                                                                                                        # print(gate_proj.reshape(-1)[:16])
                                                                                                                                # print(up_proj.reshape(-1)[:16])
                                                                                                                                        # 2. SiluAndMul
                                                                                                                                                # 使用清晰的变量名进行计算
                                                                                                                                                        print(self.act_fn(gate_proj).reshape(-1)[10976:11008])
                                                                                                                                                                x = self.act_fn(gate_proj) * up_proj

                                                                                                                                                                        # 3. down_proj
                                                                                                                                                                                print(x.reshape(-1)[10976:11008])
                                                                                                                                                                                        print(self.down_proj.weight.reshape(-1)[:16])
                                                                                                                                                                                                x = self.down_proj(x)
                                                                                                                                                                                                        print(x.reshape(-1)[:16])
                                                                                                                                                                                                                return x


                                                                                                                                                                                                            # --- 自定义算子封装 ---

                                                                                                                                                                                                            class Qwen2MLPCustom(nn.Module):
                                                                                                                                                                                                                    """
                                                                                                                                                                                                                        封装了 torch.ops._C.ffn_silu_mul 自定义算子的模块。
                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                def __init__(
                                                                                                                                                                                                                                                self,
                                                                                                                                                                                                                                                        hidden_size: int,
                                                                                                                                                                                                                                                                intermediate_size: int,
                                                                                                                                                                                                                                                                        dtype: torch.dtype,
                                                                                                                                                                                                                                                                                device: Optional[str] = None,
                                                                                                                                                                                                                                                                                    ):
                                                                                                                                                                                                                                            super().__init__()
                                                                                                                                                                                                                                                    # 权重仍然需要被定义和初始化，以便传递给自定义算子
                                                                                                                                                                                                                                                            # gate_up_weight 形状为 [hidden_size, 2 * intermediate_size]
                                                                                                                                                                                                                                                                    self.gate_up_weight = nn.Parameter(
                                                                                                                                                                                                                                                                                        torch.randn(2 * intermediate_size, hidden_size, dtype=dtype, device=device)
                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                            # down_weight 形状为 [intermediate_size, hidden_size]
                                                                                                                                                                                                                                                                                    self.down_weight = nn.Parameter(
                                                                                                                                                                                                                                                                                                        torch.randn(hidden_size, intermediate_size, dtype=dtype, device=device)
                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                        def forward(self, x: torch.Tensor) -> torch.Tensor:
                                                                                                                                                                                                                                                                                                    # 直接调用自定义算子
                                                                                                                                                                                                                                                                                                            gate_proj, up_proj = self.gate_up_weight.chunk(2, dim=0)
                                                                                                                                                                                                                                                                                                                    # print(torch.matmul(x, gate_proj.T))
                                                                                                                                                                                                                                                                                                                            # print(gate_proj, up_proj)
                                                                                                                                                                                                                                                                                                                                    return torch.ops._C.ffn(x, gate_proj, up_proj, self.down_weight)

                                                                                                                                                                                                                                                                                                                                    def load_weights_from_reference(self, reference_module: Qwen2MLPReference):
                                                                                                                                                                                                                                                                                                                                                """从参考模型加载权重，确保两者权重一致。"""
                                                                                                                                                                                                                                                                                                                                                        # Qwen2MLPReference.gate_up_proj.weight 的形状是 [2*inter_size, hidden_size]
                                                                                                                                                                                                                                                                                                                                                                # 我们需要转置它以匹配自定义算子期望的 [hidden_size, 2*inter_size]
                                                                                                                                                                                                                                                                                                                                                                        self.gate_up_weight.data.copy_(reference_module.gate_up_proj.weight)

                                                                                                                                                                                                                                                                                                                                                                                # Qwen2MLPReference.down_proj.weight 的形状是 [hidden_size, inter_size]
                                                                                                                                                                                                                                                                                                                                                                                        # 我们需要转置它以匹配自定义算子期望的 [inter_size, hidden_size]
                                                                                                                                                                                                                                                                                                                                                                                                self.down_weight.data.copy_(reference_module.down_proj.weight)


                                                                                                                                                                                                                                                                                                                                                                                                # --- Pytest 测试函数 ---

                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("num_tokens", NUM_TOKENS)
                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("hidden_size", HIDDEN_SIZES)
                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("intermediate_size", INTERMEDIATE_SIZES)
                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("dtype", DTYPES)
                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("seed", SEEDS)
                                                                                                                                                                                                                                                                                                                                                                                                @pytest.mark.parametrize("device", DEVICES)
                                                                                                                                                                                                                                                                                                                                                                                                @torch.inference_mode()
                                                                                                                                                                                                                                                                                                                                                                                                def test_ffn_correctness(
                                                                                                                                                                                                                                                                                                                                                                                                            num_tokens: int,
                                                                                                                                                                                                                                                                                                                                                                                                                hidden_size: int,
                                                                                                                                                                                                                                                                                                                                                                                                                    intermediate_size: int,
                                                                                                                                                                                                                                                                                                                                                                                                                        dtype: torch.dtype,
                                                                                                                                                                                                                                                                                                                                                                                                                            seed: int,
                                                                                                                                                                                                                                                                                                                                                                                                                                device: str,
                                                                                                                                                                                                                                                                                                                                                                                                                                ) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                            测试自定义 FFN 算子的正确性和精度。
                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                    torch.manual_seed(seed)
                                                                                                                                                                                                                                                                                                                                                                                                                        torch.npu.manual_seed_all(seed)
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                # 1. 创建参考模型和自定义模型
                                                                                                                                                                                                                                                                                                                                                                                                                                    ref_model = Qwen2MLPReference(hidden_size, intermediate_size, dtype, device=device)
                                                                                                                                                                                                                                                                                                                                                                                                                                        custom_model = Qwen2MLPCustom(hidden_size, intermediate_size, dtype, device=device)
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                # 2. 确保两个模型的权重完全相同
                                                                                                                                                                                                                                                                                                                                                                                                                                                    custom_model.load_weights_from_reference(ref_model)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # print(ref_model.gate_up_proj.weight.T)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                # print(custom_model.gate_up_weight)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 3. 创建输入张量
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input_tensor1 = torch.randn(num_tokens, hidden_size, dtype=dtype, device=device)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            input_tensor2 = input_tensor1.clone().detach()  # 完全独立的副本
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # 4. 获取参考输出和自定义算子输出
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ref_output = ref_model(input_tensor1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # print(input_tensor2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            custom_output = custom_model(input_tensor2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # custom_output = ref_output
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # 5. 比较结果
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Testing FFN: tokens={num_tokens}, hidden={hidden_size}, intermediate={intermediate_size}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                assert ref_output.shape == custom_output.shape
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert ref_output.dtype == custom_output.dtype
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            torch.testing.assert_close(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            custom_output,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ref_output,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            atol=DEFAULT_ATOL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rtol=DEFAULT_RTOL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
